# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 23:14
from __future__ import unicode_literals
# Generated by Django 2.1.dev20171120150834 on 2017-12-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_entry_dialect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='dialect',
            field=models.CharField(choices=[('Levantine', 'Levantine'), ('Egyptian', 'Egyptian'), ('Gulf', 'Gulf')], max_length=9),
        ),
    ]
